version: '3.6'
services: 
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    hostname: 'base-teste.ufnt.edu.br'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://base-teste.ufnt.edu.br'
        gitlab_rails['initial_root_password'] = 'teste@teste'
        puma['worker_processes'] = 0  # Corrigi o typo aqui (era "work_processes")
        gitlab_rails['ssl_certificate'] = "/etc/gitlab/ssl/ca.pem"
        gitlab_rails['ssl_certificate_key'] = "/etc/gitlab/ssl/ca.key"
    volumes:
      - './GITLAB_HOME/config:/etc/gitlab'
      - './GITLAB_HOME/logs:/var/log/gitlab'
      - './GITLAB_HOME/data:/var/opt/gitlab'
      - './certs:/etc/gitlab/ssl'
    shm_size: '2gb'
    networks:
      - network_base
networks:
  network_base:
